"""NEXT_STEPS_ROUND_5_FINAL.md 4: the fresh final attribution holdout.

The 487 Round 4 probes were used to filter reward models, run H1-H6, measure psi_eff, define the
C1-C5 pool, measure length dominance and inspect raw/residualized geometry. They are a CALIBRATION
set and may not carry the primary attribution claim (4.1). This module builds a disjoint final
holdout from the unused half of the same probe-prompt pool, generated by the identical base-policy
sampling procedure.

Outcome-blindness (4.4): once frozen, final-probe outcomes may not change the pool, C1-C5, DPO
hyperparameters, the attribution rule, the checkpoint choice, residualization, or standardization.
Candidate reward margins ARE computed here because they are required predictors -- that is
explicitly permitted, and it is the only thing computed on these probes before training.

Run: .venv/Scripts/python.exe -m src.judges.rm_finalholdout_r5 --filter
     .venv/Scripts/python.exe -m src.judges.rm_finalholdout_r5 --score --only <repo>
     .venv/Scripts/python.exe -m src.judges.rm_finalholdout_r5 --combine
"""
import argparse
import hashlib
import json
import os

os.environ.setdefault("PYTORCH_CUDA_ALLOC_CONF", "expandable_segments:True")

import time
from pathlib import Path

import numpy as np
import pandas as pd
from transformers import AutoTokenizer

from src.common.templating import build_scoring_inputs
from src.common.vram import reclaim
from src.data.build_prompts import load_cfg
from src.judges import rm_scorer
from src.judges.rm_harness import CTX, SHORT, load_model

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
CACHE_DIR = REPO_ROOT / "data_cache"
RESULTS_DIR = REPO_ROOT / "results"
RAW = CACHE_DIR / "response_pairs_probe_final.jsonl"
MIN_RETAINED_FRACTION = 0.60


def pool() -> list[str]:
    S = json.load(open(RESULTS_DIR / "rm_calibration_r5.json"))["S"]
    return [r for r, s in SHORT.items() if s in S]


def base_len_diff(ptok, pairs: list[dict]) -> np.ndarray:
    """Standing convention: len(y) - len(y') in base-policy tokens."""
    return np.array([len(ptok.encode(p["response_a"])) - len(ptok.encode(p["response_b"]))
                     for p in pairs], dtype=float)


def do_filter() -> None:
    cfg = load_cfg()
    policy_cap = cfg["dpo"]["max_length"]
    repos = pool()
    raw = [json.loads(l) for l in open(RAW)]
    print(f"fresh raw probes: {len(raw)}   pool: {[SHORT[r] for r in repos]}")

    # 4.2 disjointness assertions, checked rather than asserted in prose
    cal_prompts = {json.loads(l)["prompt"] for l in open(CACHE_DIR / "response_pairs_probe.jsonl")}
    tr_prompts = {json.loads(l)["prompt"] for l in open(CACHE_DIR / "response_pairs_train.jsonl")}
    new_prompts = [p["prompt"] for p in raw]
    dis = {"n_raw": len(raw), "n_unique_prompts": len(set(new_prompts)),
           "overlap_with_calibration_probes": len(set(new_prompts) & cal_prompts),
           "overlap_with_training_pairs": len(set(new_prompts) & tr_prompts)}
    print(f"disjointness: {dis}")
    assert dis["overlap_with_calibration_probes"] == 0, "final holdout overlaps the calibration probes"
    assert dis["overlap_with_training_pairs"] == 0, "final holdout overlaps the training prompts"

    toks = {r: AutoTokenizer.from_pretrained(r) for r in repos}
    ptok = AutoTokenizer.from_pretrained(cfg["models"]["base_policy"])
    lens = {SHORT[r]: np.zeros(len(raw), dtype=int) for r in repos}
    lens["policy(Qwen)"] = np.zeros(len(raw), dtype=int)
    for i, p in enumerate(raw):
        for r in repos:
            lens[SHORT[r]][i] = max(
                len(toks[r].encode(rm_scorer.serialize(p["prompt"], p[w]), add_special_tokens=True))
                for w in ("response_a", "response_b"))
        lens["policy(Qwen)"][i] = max(
            build_scoring_inputs(ptok, p["prompt"], p[w])[0].shape[0]
            for w in ("response_a", "response_b"))

    caps = {SHORT[r]: CTX[r] for r in repos}
    caps["policy(Qwen)"] = policy_cap
    over = {k: lens[k] > caps[k] for k in lens}
    bad = np.zeros(len(raw), dtype=bool)
    for v in over.values():
        bad |= v
    keep = [i for i in range(len(raw)) if not bad[i]]

    tbl = pd.DataFrame([{"scorer": k, "context_cap": caps[k], "max_realized_len": int(lens[k].max()),
                         "median": int(np.median(lens[k])), "p99": int(np.percentile(lens[k], 99)),
                         "excluded_by_this_scorer": int(over[k].sum())} for k in lens])
    print("\n=== 4.3 final-holdout compatibility filter ===")
    print(tbl.to_string(index=False))
    frac = len(keep) / len(raw)
    ok = frac >= MIN_RETAINED_FRACTION
    print(f"\nN_final = {len(keep)}   retained fraction = {frac:.4f}   "
          f"gate (>= {MIN_RETAINED_FRACTION}): {'PASS' if ok else 'STOP'}")

    sub = [raw[i] for i in keep]
    manifest = hashlib.sha256(json.dumps(
        [{"i": i, "prompt": raw[i]["prompt"], "a": raw[i]["response_a"], "b": raw[i]["response_b"]}
         for i in keep], sort_keys=True).encode()).hexdigest()
    with open(CACHE_DIR / "final_holdout.jsonl", "w") as f:
        for i in keep:
            f.write(json.dumps({"final_idx": i, **raw[i]}) + "\n")
    out = {"n_raw": len(raw), "N_final": len(keep), "retained_fraction": frac,
           "min_retained_fraction": MIN_RETAINED_FRACTION, "gate_pass": ok,
           "disjointness": dis, "per_scorer": tbl.to_dict(orient="records"),
           "retained_indices": keep, "manifest_sha256": manifest,
           "len_diff": base_len_diff(ptok, sub).tolist(),
           "source": "prompt_splits.probe_prompts[600:1200], unused half of the same pool",
           "generation": "identical base-policy procedure; temperature, top_p, max_new_tokens, "
                         "chat template and sampling policy unchanged"}
    with open(RESULTS_DIR / "final_holdout.json", "w") as f:
        json.dump(out, f)
    print(f"manifest sha256 = {manifest}")
    print(f"wrote data_cache/final_holdout.jsonl and results/final_holdout.json")


def do_score(repo: str) -> None:
    pairs = [json.loads(l) for l in open(CACHE_DIR / "final_holdout.jsonl")]
    model, tok = load_model(repo)
    t0 = time.time()
    _, _, d = rm_scorer.score_pairs(model, tok, pairs, "cuda", CTX[repo])
    del model
    reclaim()
    p = RESULTS_DIR / f"final_margins_{repo.replace('/', '__')}.json"
    with open(p, "w") as f:
        json.dump({"model": repo, "n": len(pairs), "d_m": d.numpy().tolist(),
                   "wall_clock_s": time.time() - t0}, f)
    print(f"{SHORT[repo]}: scored {len(pairs)} final probes in {time.time() - t0:.0f}s -> {p.name}")


def do_combine() -> None:
    """4.5: apply the FROZEN calibration transforms out of sample. Nothing here is fitted on the
    final probes -- mu/sd and the length coefficients all come from the 487 calibration probes."""
    cal = json.load(open(RESULTS_DIR / "rm_calibration_r5.json"))
    fh = json.load(open(RESULTS_DIR / "final_holdout.json"))
    tf = cal["calibration_transforms"]
    x = np.array(fh["len_diff"])
    S = cal["S"]

    raw, std, resid_std = {}, {}, {}
    for m in S:
        repo = [r for r, s in SHORT.items() if s == m][0]
        d = np.array(json.load(open(RESULTS_DIR / f"final_margins_{repo.replace('/', '__')}.json"))["d_m"])
        t = tf[m]
        raw[m] = d
        std[m] = (d - t["mu_cal"]) / t["sd_cal"]
        r = d - (t["c_len"] + t["gamma_len"] * x)
        resid_std[m] = (r - t["resid_mean_cal"]) / t["resid_sd_cal"]

    D_std = np.column_stack([std[m] for m in S])
    D_res = np.column_stack([resid_std[m] for m in S])
    Craw = np.corrcoef(D_std.T)
    Cres = np.corrcoef(D_res.T)
    print("=== final-holdout candidate correlation (raw standardized) ===")
    print(pd.DataFrame(Craw, index=S, columns=S).round(3).to_string())
    print("\n=== final-holdout candidate correlation (length-residualized) ===")
    print(pd.DataFrame(Cres, index=S, columns=S).round(3).to_string())
    iu = np.triu_indices(len(S), k=1)
    praw = np.degrees(np.arccos(np.clip(Craw, -1, 1)))
    pres = np.degrees(np.arccos(np.clip(Cres, -1, 1)))
    print(f"\nmin pairwise psi_eff on the FINAL holdout: raw {praw[iu].min():.2f} deg, "
          f"residualized {pres[iu].min():.2f} deg  (reported; the C5 gate was evaluated on "
          f"calibration probes and is not re-run here)")

    out = {"S": S, "N_final": D_std.shape[0],
           "D_std": D_std.tolist(), "D_resid_std": D_res.tolist(),
           "corr_raw_final": Craw.tolist(), "corr_resid_final": Cres.tolist(),
           "psi_raw_final": praw.tolist(), "psi_resid_final": pres.tolist(),
           "min_psi_raw_final": float(praw[iu].min()), "min_psi_resid_final": float(pres[iu].min()),
           "transforms_source": "frozen 487-probe calibration set (4.5); nothing fitted on final probes"}
    with open(RESULTS_DIR / "final_design_matrix.json", "w") as f:
        json.dump(out, f)
    print(f"wrote {RESULTS_DIR / 'final_design_matrix.json'}")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--filter", action="store_true")
    ap.add_argument("--score", action="store_true")
    ap.add_argument("--only")
    ap.add_argument("--combine", action="store_true")
    a = ap.parse_args()
    if a.filter:
        do_filter()
    elif a.score:
        do_score(a.only)
    elif a.combine:
        do_combine()


if __name__ == "__main__":
    main()
